from __future__ import annotations



class PropertyAddress:    
    def __init__(self, address_id: str) -> None: ...
    def __eq__(self, other: PropertyAddress) -> bool: ...    
    def __repr__(self) -> str: ...

    @property
    def address_id(self) -> str: ...

    @property
    def bfe(self) -> int: ...

    @property
    def address(self) -> str: ...

    @property
    def general_info(self) -> dict[str, int | str | list]: ...

    @property
    def entire_property_info(self) -> dict[str, dict[str, str | int | list] | int | None]: ...
              
    @property
    def address_history(self) -> dict[str, list, dict, None, int]: ...
            
    @property
    def sales_history(self) -> list[dict[str, int | str]]: ...
    
    @property
    def valuation_history(self) -> list[dict[str, int | str]]: ...
